### ISSUE TITLE
Remove VITE_*

### ISSUE THREAD

**Issue by orefalo** [jmagrippis/with-svelte#19]
https://github.com/jmagrippis/with-svelte/blob/71f44a1425cdc1c93f9e91dc9bc7c4069706abda/src/env.d.ts#L7

Since these two are PRIVATE... I believe you should remove the VITE* prefix to prevent ANY unpredicted client bundleling.

```
// NEVER EXPOSE
readonly FIREBASE_ADMIN_CLIENT_EMAIL: string
readonly FIREBASE_ADMIN_PRIVATE_KEY: string
```

**Comment by orefalo** [comment]
FYI, while I am convinced it's the right approach to avoid mistakes. It does require code chance.

... now I see the issue everyone complains about with ENV variables.  Sveltekit is confusing indeed.

Let me look for a solution

**Comment by orefalo** [comment]
Here is my solution, based on https://vadosware.io/post/pattern-for-env-in-sveltekit/

In summary:
* Any ENV starting with VITE_ can leak to the client
* on the contrary, any ENV NOT starting with VITE will never leak to the client
* this requires dotenv, which is only loaded for local dev testing

```
import { browser, dev } from '$app/env';
import * as path from 'path';

let env;

export const loadEnv = async () => {
	if (!browser && dev) {

		// Import and load .env (we use .envrc to match local env files, but it could easily be .env)
		const dotenv = await import('dotenv');
		const loaded = dotenv.config({
			path: path.resolve(process.cwd(), '.env')
		});
		if (loaded.error) {
			throw loaded.error;
		}
		env = loaded.parsed;
	} else {
		console.log('loadEnv on browser or prod, skipping as it should be preset from the platform ENV variables');
		env = process.env;
	}
};

export const getServerOnlyEnvVar = (key) => {
	return env[key];
};
```

with these changes, you `admin.ts` code becomes:
```

const env=loadEnv()

if (
	!import.meta.env.VITE_FIREBASE_PROJECT_ID ||
	 !getServerOnlyEnvVar(env, "FIREBASE_ADMIN_CLIENT_EMAIL") ||
	 !getServerOnlyEnvVar(env, "FIREBASE_ADMIN_PRIVATE_KEY")
)
{
	throw new Error('Firebase Admin environment variables not set');
}

const projectId = import.meta.env.VITE_FIREBASE_PROJECT_ID;
const apiKey = import.meta.env.VITE_FIREBASE_API_KEY;
const clientEmail = getServerOnlyEnvVar(env, "FIREBASE_ADMIN_CLIENT_EMAIL")
const privateKey = getServerOnlyEnvVar(env, "FIREBASE_ADMIN_PRIVATE_KEY").replace(/\\n/g, '\n');
```

**Comment by jmagrippis** [comment]
Hey @orefalo ! Thanks for raising this!

I think you've seen my "Fullstack SvelteKit Auth 🔐 with Firebase & Magic Links! 🪄" video, but I'll paste a link here, with a timestamp where we're creating this file and talking about this "leakage" issue!

https://youtu.be/MAHE4iQgh5Q?t=1487

I did pace around the room scratching my head a little bit when "scripting" the video when it came to this point! 😄

In the end, given it's a super long video already, I decided against bringing in and explaining dotenv or whichever other "safer" solution, and instead stressed and stressed again that we shouldn't leak these and we should avoid using them in frontend files!

--

But of course, that was the easy way out, as really... I couldn't find a great way to safeguard against using a server-only env variable on the client!

I **think** I like your solution more, but I'm still not sure if mixing the way Vite uses env vars, where they also use dotenv but then they statically replace the imports with string literal values, with our custom use of dotenv is the best idea...

I'm editing a video on Vitest now, but I'll give your idea a go afterwards (probably using [dotenv-flow](https://www.npmjs.com/package/dotenv-flow) while we're at it?).

If it's only about having these variables available via a `.env` file during dev or testing, maybe we could "just" require dotenv-flow anyway when running the dev server (or before the tests) instead of having to `loadEnv`, and having the `getServerOnlyEnvVar` method check if we're on the browser before returning `process.env[key]`, or crashing with an error!

```ts
import { browser } from '$app/env';

export const getServerOnlyEnvVar = (key: string) => {
  if (browser) {
    throw new Error('attempting to access server-only env var on the browser)
  }
  return process.env[key];
};
```

Thanks again for this, will ping you again soon ™️ 😄

**Comment by orefalo** [comment]
didn't know about `dotflow-flow` - definitly a better alternative.

your suggestion works as well. I need to experiment further with vercel to see if it has any issues.
   so far it's the only reason I am not runnning dotenv beyond dev & test modes

anyways.. glad it helped.

**Comment by orefalo** [comment]
Finised implementing your proposal.
it's lighter, simplier than mine. Thank you

you may close this ticket...

Sincerely,

**Comment by jmagrippis** [comment]
Haha, yeah, I finally uploaded that video, so I had time to tackle your suggestion while YouTube was processing the HD versions 😄!

Interesting change, makes it a bit easier to test without messing with `process.env` I suppose, but it's still not a pure method since it's got that magic `browser` variable! Have you ever called it with something besides `process`?

**Comment by orefalo** [comment]
I haven't.
I've been wondering why.. and came across several thread that talk about how referencing process.env can load all variables in the UI. Not sure if it's funded... but since this serious project uses it ... why not.

I did add the browser check temporary to trap any side effects I may not be aware of.

are you on discord? might be easier to chat.
